// Code generated by qtc from "gen.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/tailpipe/gen.qtpl:1
package tailpipe

//line pkg/tailpipe/gen.qtpl:1
import (
	"github.com/mazznoer/csscolorparser"
	"log"
	"strconv"
)

//line pkg/tailpipe/gen.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/tailpipe/gen.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/tailpipe/gen.qtpl:6
func streamgenerateFromConfig(qw422016 *qt422016.Writer, cfg TailPipeConfig) {
//line pkg/tailpipe/gen.qtpl:6
	qw422016.N().S(`package tailpipe

import (
    "fmt"
    "strings"
	"golang.org/x/exp/slices"
	"k8s.io/apimachinery/pkg/util/sets"
)


type TailPipe struct {
    classes sets.Set[string]
    combined     string
}

func NewTailPipe() *TailPipe {
	return &TailPipe{
        classes: sets.New(`)
//line pkg/tailpipe/gen.qtpl:6
	qw422016.N().S("`")
//line pkg/tailpipe/gen.qtpl:6
	qw422016.N().S(`
// Default margins are removed
// Preflight removes all of the default margins from elements like headings, blockquotes, paragraphs, etc.
// This makes it harder to accidentally rely on margin values applied by the user-agent stylesheet that are not part of your spacing scale.
blockquote,
dl,
dd,
h1,
h2,
h3,
h4,
h5,
h6,
hr,
figure,
p,
pre {
  margin: 0;
}

// Headings are unstyled
// All heading elements are completely unstyled by default, and have the same font-size and font-weight as normal text.
// The reason for this is two-fold:
// *  It helps you avoid accidentally deviating from your type scale. By default, browsers assign sizes to headings that don’t exist in Tailwind’s default type scale, and aren’t guaranteed to exist in your own type scale.
// * In UI development, headings should often be visually de-emphasized. Making headings unstyled by default means any styling you apply to headings happens consciously and deliberately.
h1,
h2,
h3,
h4,
h5,
h6 {
  font-size: inherit;
  font-weight: inherit;
}

// Lists are unstyled
// Ordered and unordered lists are unstyled by default, with no bullets/numbers and no margin or padding.
// If you’d like to style a list, you can do so using the list-style-type and list-style-position utilities
ol,
ul {
  list-style: none;
  margin: 0;
  padding: 0;
}

// Images are block-level
// Images and other replaced elements (like svg, video, canvas, and others) are display: block by default.
// This helps to avoid unexpected alignment issues that you often run into using the browser default of display: inline.
// If you ever need to make one of these elements inline instead of block, simply use the inline utility:
img,
svg,
video,
canvas,
audio,
iframe,
embed,
object {
  display: block;
  vertical-align: middle;
}

// Images are constrained to the parent width
// Images and videos are constrained to the parent width in a way that preserves their intrinsic aspect ratio.
// This prevents them from overflowing their containers and makes them responsive by default. If you ever need to override this behavior, use the max-w-none utility:
img,
video {
  max-width: 100%;
  height: auto;
}

// Border styles are reset globally
// In order to make it easy to add a border by simply adding the border class, Tailwind overrides the default border styles for all elements with the following rules:
// Since the border class only sets the border-width property, this reset ensures that adding that class always adds a solid 1px border using your configured default border color.
// This can cause some unexpected results when integrating certain third-party libraries, like Google maps for example.
*,
::before,
::after {
  border-width: 0;
  border-style: solid;
  border-color: theme('borderColor.DEFAULT', currentColor);
}

// To ensure that we provide accessible styles out of the box, we made sure that buttons have a default outline. You can of course override this by applying focus:ring or similar utilities to your buttons.
button:focus {
  outline: 1px dotted;
  outline: 5px auto -webkit-focus-ring-color;
}
`)
//line pkg/tailpipe/gen.qtpl:6
	qw422016.N().S("`")
//line pkg/tailpipe/gen.qtpl:6
	qw422016.N().S(`,
        ),
	}
}

func (p *TailPipe) generate() string {
    arr := p.classes.UnsortedList()
    slices.Sort(arr)
    return strings.Join(arr, "\n")
}

func (p *TailPipe) CombinedClasses() string {
    return p.combined
}

type AtomicClass struct {
    parent *TailPipe
    classes sets.Set[string]
}

func (p *TailPipe) Atomic() *AtomicClass {
    ac := &AtomicClass{parent: p}
    return ac
}

func (ac *AtomicClass) Build() string {
    arr := ac.classes.UnsortedList()
    slices.SortFunc(arr, func(a, b string) bool {
        // Replace with Headwind sort
        return a < b
    })
    return strings.Join(arr, " ")
}

func(ac *AtomicClass) upsertClass(groupName, name string, values ...string) *AtomicClass {
    cls := fmt.Sprintf("%s-%s",groupName , name)

    if strings.ToUpper(name) == "DEFAULT" {
        name = ""
        cls = groupName
    }
    if ac.classes.Has(cls) {
        return ac
    }
    ac.classes.Insert(cls)

    for i, v := range values {
        values[i] = fmt.Sprintf("%s;", v)
    }

    css := fmt.Sprintf(`)
//line pkg/tailpipe/gen.qtpl:6
	qw422016.N().S("`")
//line pkg/tailpipe/gen.qtpl:6
	qw422016.N().S(`.%s {
        "%s";
    }`)
//line pkg/tailpipe/gen.qtpl:6
	qw422016.N().S("`")
//line pkg/tailpipe/gen.qtpl:6
	qw422016.N().S(`, cls, strings.Join( values,"\n"))

    ac.parent.classes.Insert(css)
    return ac
}

// Animations
`)
//line pkg/tailpipe/gen.qtpl:170
	for _, kv := range cfg.Animation.SortedKV() {
//line pkg/tailpipe/gen.qtpl:170
		qw422016.N().S(`func (ac *AtomicClass) Animate`)
//line pkg/tailpipe/gen.qtpl:171
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:171
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("animate", "`)
//line pkg/tailpipe/gen.qtpl:172
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:172
		qw422016.N().S(`","`)
//line pkg/tailpipe/gen.qtpl:172
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:172
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:175
	}
//line pkg/tailpipe/gen.qtpl:175
	qw422016.N().S(`

// Aria TODO: Implement aria https://tailwindcss.com/docs/hover-focus-and-other-states#aria-states

// AspectRatio
`)
//line pkg/tailpipe/gen.qtpl:180
	for _, kv := range cfg.AspectRatio.SortedKV() {
//line pkg/tailpipe/gen.qtpl:180
		qw422016.N().S(`func (ac *AtomicClass) AspectRatio`)
//line pkg/tailpipe/gen.qtpl:181
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:181
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("aspect-ratio", "`)
//line pkg/tailpipe/gen.qtpl:182
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:182
		qw422016.N().S(`","`)
//line pkg/tailpipe/gen.qtpl:182
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:182
		qw422016.N().S(`}")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:185
	}
//line pkg/tailpipe/gen.qtpl:185
	qw422016.N().S(`

// Backdrop Filter
`)
//line pkg/tailpipe/gen.qtpl:188
	for _, kv := range cfg.BackdropFilter.Blur.SortedKV() {
//line pkg/tailpipe/gen.qtpl:188
		qw422016.N().S(`func (ac *AtomicClass) BackdropBlur`)
//line pkg/tailpipe/gen.qtpl:189
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:189
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("backdrop-blur", "`)
//line pkg/tailpipe/gen.qtpl:190
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:190
		qw422016.N().S(`", "backdrop-filter: blur(`)
//line pkg/tailpipe/gen.qtpl:190
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:190
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:193
	}
//line pkg/tailpipe/gen.qtpl:193
	qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:194
	for _, kv := range cfg.BackdropFilter.Brightness.SortedKV() {
//line pkg/tailpipe/gen.qtpl:194
		qw422016.N().S(`func (ac *AtomicClass) BackdropBrightness`)
//line pkg/tailpipe/gen.qtpl:195
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:195
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("backdrop-brightness", "`)
//line pkg/tailpipe/gen.qtpl:196
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:196
		qw422016.N().S(`", "backdrop-filter: brightness(`)
//line pkg/tailpipe/gen.qtpl:196
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:196
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:199
	}
//line pkg/tailpipe/gen.qtpl:199
	qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:200
	for _, kv := range cfg.BackdropFilter.Contrast.SortedKV() {
//line pkg/tailpipe/gen.qtpl:200
		qw422016.N().S(`func (ac *AtomicClass) BackdropContrast`)
//line pkg/tailpipe/gen.qtpl:201
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:201
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("backdrop-contrast", "`)
//line pkg/tailpipe/gen.qtpl:202
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:202
		qw422016.N().S(`", "backdrop-filter: contrast(`)
//line pkg/tailpipe/gen.qtpl:202
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:202
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:205
	}
//line pkg/tailpipe/gen.qtpl:205
	qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:206
	for _, kv := range cfg.BackdropFilter.Grayscale.SortedKV() {
//line pkg/tailpipe/gen.qtpl:206
		qw422016.N().S(`func (ac *AtomicClass) BackdropGrayscale`)
//line pkg/tailpipe/gen.qtpl:207
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:207
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("backdrop-grayscale", "`)
//line pkg/tailpipe/gen.qtpl:208
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:208
		qw422016.N().S(`", "backdrop-filter: grayscale(`)
//line pkg/tailpipe/gen.qtpl:208
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:208
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:211
	}
//line pkg/tailpipe/gen.qtpl:211
	qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:212
	for _, kv := range cfg.BackdropFilter.HueRotate.SortedKV() {
//line pkg/tailpipe/gen.qtpl:212
		qw422016.N().S(`func (ac *AtomicClass) BackdropHueRotate`)
//line pkg/tailpipe/gen.qtpl:213
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:213
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("backdrop-hue-rotate", "`)
//line pkg/tailpipe/gen.qtpl:214
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:214
		qw422016.N().S(`", "backdrop-filter: hue-rotate(`)
//line pkg/tailpipe/gen.qtpl:214
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:214
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:217
	}
//line pkg/tailpipe/gen.qtpl:217
	qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:218
	for _, kv := range cfg.BackdropFilter.Invert.SortedKV() {
//line pkg/tailpipe/gen.qtpl:218
		qw422016.N().S(`func (ac *AtomicClass) BackdropInvert`)
//line pkg/tailpipe/gen.qtpl:219
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:219
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("backdrop-invert", "`)
//line pkg/tailpipe/gen.qtpl:220
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:220
		qw422016.N().S(`", "backdrop-filter: invert(`)
//line pkg/tailpipe/gen.qtpl:220
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:220
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:223
	}
//line pkg/tailpipe/gen.qtpl:223
	qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:224
	for _, kv := range cfg.BackdropFilter.Opacity.SortedKV() {
//line pkg/tailpipe/gen.qtpl:224
		qw422016.N().S(`func (ac *AtomicClass) BackdropOpacity`)
//line pkg/tailpipe/gen.qtpl:225
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:225
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("backdrop-opacity", "`)
//line pkg/tailpipe/gen.qtpl:226
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:226
		qw422016.N().S(`", "backdrop-filter: opacity(`)
//line pkg/tailpipe/gen.qtpl:226
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:226
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:229
	}
//line pkg/tailpipe/gen.qtpl:229
	qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:230
	for _, kv := range cfg.BackdropFilter.Saturate.SortedKV() {
//line pkg/tailpipe/gen.qtpl:230
		qw422016.N().S(`func (ac *AtomicClass) BackdropSaturate`)
//line pkg/tailpipe/gen.qtpl:231
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:231
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("backdrop-saturate", "`)
//line pkg/tailpipe/gen.qtpl:232
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:232
		qw422016.N().S(`", "backdrop-filter: saturate(`)
//line pkg/tailpipe/gen.qtpl:232
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:232
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:235
	}
//line pkg/tailpipe/gen.qtpl:235
	qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:236
	for _, kv := range cfg.BackdropFilter.Sepia.SortedKV() {
//line pkg/tailpipe/gen.qtpl:236
		qw422016.N().S(`func (ac *AtomicClass) BackdropSepia`)
//line pkg/tailpipe/gen.qtpl:237
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:237
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("backdrop-sepia", "`)
//line pkg/tailpipe/gen.qtpl:238
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:238
		qw422016.N().S(`", "backdrop-filter: sepia(`)
//line pkg/tailpipe/gen.qtpl:238
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:238
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:241
	}
//line pkg/tailpipe/gen.qtpl:241
	qw422016.N().S(`

// Background
`)
//line pkg/tailpipe/gen.qtpl:244
	for _, kv := range cfg.Background.Color.SortedKV() {
//line pkg/tailpipe/gen.qtpl:246
		bgColor, err := csscolorparser.Parse(kv.Value)
		bg := kv.Value
		isColor := err == nil
		if err == nil {
			bg = bgColor.HexString()
		}

//line pkg/tailpipe/gen.qtpl:252
		qw422016.N().S(`func (ac *AtomicClass) BG`)
//line pkg/tailpipe/gen.qtpl:253
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:253
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("bg", "`)
//line pkg/tailpipe/gen.qtpl:254
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:254
		qw422016.N().S(`", "background-color: `)
//line pkg/tailpipe/gen.qtpl:254
		qw422016.E().S(bg)
//line pkg/tailpipe/gen.qtpl:254
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:257
		if isColor {
//line pkg/tailpipe/gen.qtpl:257
			qw422016.N().S(`
// Background Opacity
`)
//line pkg/tailpipe/gen.qtpl:259
			for _, opacityKV := range cfg.Background.Opacity.SortedKV() {
//line pkg/tailpipe/gen.qtpl:261
				opacity, err := strconv.ParseFloat(opacityKV.Value, 64)
				if err != nil {
					log.Printf("%+v XXX %v", opacityKV, err)
					continue
				}
				bgWithOpacity := bgColor
				bgWithOpacity.A = opacity
				bgWithOpacityStr := bgWithOpacity.HexString()

//line pkg/tailpipe/gen.qtpl:269
				qw422016.N().S(`func (ac *AtomicClass) BG`)
//line pkg/tailpipe/gen.qtpl:270
				qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:270
				qw422016.N().S(`_`)
//line pkg/tailpipe/gen.qtpl:270
				qw422016.E().S(atomicName(opacityKV.Key))
//line pkg/tailpipe/gen.qtpl:270
				qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("bg","`)
//line pkg/tailpipe/gen.qtpl:271
				qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:271
				qw422016.N().S(`/`)
//line pkg/tailpipe/gen.qtpl:271
				qw422016.E().S(opacityKV.Key)
//line pkg/tailpipe/gen.qtpl:271
				qw422016.N().S(`", "background-color: `)
//line pkg/tailpipe/gen.qtpl:271
				qw422016.E().S(bgWithOpacityStr)
//line pkg/tailpipe/gen.qtpl:271
				qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:274
			}
//line pkg/tailpipe/gen.qtpl:274
			qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:275
		}
//line pkg/tailpipe/gen.qtpl:275
		qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:276
	}
//line pkg/tailpipe/gen.qtpl:276
	qw422016.N().S(`

// BG Image
`)
//line pkg/tailpipe/gen.qtpl:279
	for _, kv := range cfg.Background.Image.SortedKV() {
//line pkg/tailpipe/gen.qtpl:279
		qw422016.N().S(`func (ac *AtomicClass) BG`)
//line pkg/tailpipe/gen.qtpl:280
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:280
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("bg", "`)
//line pkg/tailpipe/gen.qtpl:281
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:281
		qw422016.N().S(`", "background-image: `)
//line pkg/tailpipe/gen.qtpl:281
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:281
		qw422016.N().S(`")
    return  ac
}
`)
//line pkg/tailpipe/gen.qtpl:284
	}
//line pkg/tailpipe/gen.qtpl:284
	qw422016.N().S(`

// BG Position
`)
//line pkg/tailpipe/gen.qtpl:287
	for _, kv := range cfg.Background.Position.SortedKV() {
//line pkg/tailpipe/gen.qtpl:287
		qw422016.N().S(`func (ac *AtomicClass) BG`)
//line pkg/tailpipe/gen.qtpl:288
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:288
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("bg", "`)
//line pkg/tailpipe/gen.qtpl:289
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:289
		qw422016.N().S(`", "background-position: `)
//line pkg/tailpipe/gen.qtpl:289
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:289
		qw422016.N().S(`")
    return  ac
}
`)
//line pkg/tailpipe/gen.qtpl:292
	}
//line pkg/tailpipe/gen.qtpl:292
	qw422016.N().S(`

// BG Size
`)
//line pkg/tailpipe/gen.qtpl:295
	for _, kv := range cfg.Background.Size.SortedKV() {
//line pkg/tailpipe/gen.qtpl:295
		qw422016.N().S(`func (ac *AtomicClass) BG`)
//line pkg/tailpipe/gen.qtpl:296
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:296
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("bg", "`)
//line pkg/tailpipe/gen.qtpl:297
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:297
		qw422016.N().S(`", "background-size: `)
//line pkg/tailpipe/gen.qtpl:297
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:297
		qw422016.N().S(`")
    return  ac
}
`)
//line pkg/tailpipe/gen.qtpl:300
	}
//line pkg/tailpipe/gen.qtpl:300
	qw422016.N().S(`

// Blur
`)
//line pkg/tailpipe/gen.qtpl:303
	for _, kv := range cfg.Blur.SortedKV() {
//line pkg/tailpipe/gen.qtpl:303
		qw422016.N().S(`func (ac *AtomicClass) Blur`)
//line pkg/tailpipe/gen.qtpl:304
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:304
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("blur", "`)
//line pkg/tailpipe/gen.qtpl:305
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:305
		qw422016.N().S(`", "filter: blur(`)
//line pkg/tailpipe/gen.qtpl:305
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:305
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:308
	}
//line pkg/tailpipe/gen.qtpl:308
	qw422016.N().S(`

// Border
`)
//line pkg/tailpipe/gen.qtpl:311
	for _, kv := range cfg.Border.Color.SortedKV() {
//line pkg/tailpipe/gen.qtpl:313
		borderColor, err := csscolorparser.Parse(kv.Value)
		border := kv.Value
		isColor := err == nil
		if err == nil {
			border = borderColor.HexString()
		}

//line pkg/tailpipe/gen.qtpl:319
		qw422016.N().S(`func (ac *AtomicClass) Border`)
//line pkg/tailpipe/gen.qtpl:320
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:320
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("border", "`)
//line pkg/tailpipe/gen.qtpl:321
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:321
		qw422016.N().S(`", "border-color: `)
//line pkg/tailpipe/gen.qtpl:321
		qw422016.E().S(border)
//line pkg/tailpipe/gen.qtpl:321
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:324
		if isColor {
//line pkg/tailpipe/gen.qtpl:324
			qw422016.N().S(`
// Border Opacity
`)
//line pkg/tailpipe/gen.qtpl:326
			for _, opacityKV := range cfg.Border.Opacity.SortedKV() {
//line pkg/tailpipe/gen.qtpl:328
				opacity, err := strconv.ParseFloat(opacityKV.Value, 64)
				if err != nil {
					log.Printf("%+v XXX %v", opacityKV, err)
					continue
				}
				borderWithOpacity := borderColor
				borderWithOpacity.A = opacity
				borderWithOpacityStr := borderWithOpacity.HexString()

//line pkg/tailpipe/gen.qtpl:336
				qw422016.N().S(`func (ac *AtomicClass) Border`)
//line pkg/tailpipe/gen.qtpl:337
				qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:337
				qw422016.N().S(`_`)
//line pkg/tailpipe/gen.qtpl:337
				qw422016.E().S(atomicName(opacityKV.Key))
//line pkg/tailpipe/gen.qtpl:337
				qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("border","`)
//line pkg/tailpipe/gen.qtpl:338
				qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:338
				qw422016.N().S(`/`)
//line pkg/tailpipe/gen.qtpl:338
				qw422016.E().S(opacityKV.Key)
//line pkg/tailpipe/gen.qtpl:338
				qw422016.N().S(`", "border-color: `)
//line pkg/tailpipe/gen.qtpl:338
				qw422016.E().S(borderWithOpacityStr)
//line pkg/tailpipe/gen.qtpl:338
				qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:341
			}
//line pkg/tailpipe/gen.qtpl:341
			qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:342
		}
//line pkg/tailpipe/gen.qtpl:342
		qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:343
	}
//line pkg/tailpipe/gen.qtpl:343
	qw422016.N().S(`

// Border Radius
`)
//line pkg/tailpipe/gen.qtpl:346
	for _, kv := range cfg.Border.Radius.SortedKV() {
//line pkg/tailpipe/gen.qtpl:346
		qw422016.N().S(`func (ac *AtomicClass) Rounded`)
//line pkg/tailpipe/gen.qtpl:347
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:347
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("rounded", "`)
//line pkg/tailpipe/gen.qtpl:348
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:348
		qw422016.N().S(`", "border-radius: `)
//line pkg/tailpipe/gen.qtpl:348
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:348
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:351
	}
//line pkg/tailpipe/gen.qtpl:351
	qw422016.N().S(`

// Border Spacing
`)
//line pkg/tailpipe/gen.qtpl:354
	for _, kv := range cfg.Border.Spacing.SortedKV() {
//line pkg/tailpipe/gen.qtpl:354
		qw422016.N().S(`func (ac *AtomicClass) BorderSpacing`)
//line pkg/tailpipe/gen.qtpl:355
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:355
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("border-spacing", "`)
//line pkg/tailpipe/gen.qtpl:356
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:356
		qw422016.N().S(`", "border-spacing: `)
//line pkg/tailpipe/gen.qtpl:356
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:356
		qw422016.N().S(` `)
//line pkg/tailpipe/gen.qtpl:356
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:356
		qw422016.N().S(`")
    return ac
}
func (ac *AtomicClass) BorderSpacingX`)
//line pkg/tailpipe/gen.qtpl:359
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:359
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("border-spacing-x", "`)
//line pkg/tailpipe/gen.qtpl:360
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:360
		qw422016.N().S(`", "border-spacing-x: `)
//line pkg/tailpipe/gen.qtpl:360
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:360
		qw422016.N().S(` var(--tw-border-spacing-y)")
    return ac
}
func (ac *AtomicClass) BorderSpacingY`)
//line pkg/tailpipe/gen.qtpl:363
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:363
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("border-spacing-y", "`)
//line pkg/tailpipe/gen.qtpl:364
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:364
		qw422016.N().S(`", "border-spacing-y: var(--tw-border-spacing-x) `)
//line pkg/tailpipe/gen.qtpl:364
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:364
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:367
	}
//line pkg/tailpipe/gen.qtpl:367
	qw422016.N().S(`

// Border Width
`)
//line pkg/tailpipe/gen.qtpl:370
	for _, kv := range cfg.Border.Width.SortedKV() {
//line pkg/tailpipe/gen.qtpl:370
		qw422016.N().S(`func (ac *AtomicClass) Border`)
//line pkg/tailpipe/gen.qtpl:371
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:371
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("border", "`)
//line pkg/tailpipe/gen.qtpl:372
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:372
		qw422016.N().S(`", "border-width: `)
//line pkg/tailpipe/gen.qtpl:372
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:372
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:375
	}
//line pkg/tailpipe/gen.qtpl:375
	qw422016.N().S(`

// Box Shadow
`)
//line pkg/tailpipe/gen.qtpl:378
	for _, kv := range cfg.BoxShadow.Value.SortedKV() {
//line pkg/tailpipe/gen.qtpl:378
		qw422016.N().S(`func (ac *AtomicClass) Shadow`)
//line pkg/tailpipe/gen.qtpl:379
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:379
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("shadow", "`)
//line pkg/tailpipe/gen.qtpl:380
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:380
		qw422016.N().S(`", "box-shadow: `)
//line pkg/tailpipe/gen.qtpl:380
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:380
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:383
	}
//line pkg/tailpipe/gen.qtpl:383
	qw422016.N().S(`

// Box Shadow Color
`)
//line pkg/tailpipe/gen.qtpl:386
	for _, kv := range cfg.BoxShadow.Color.SortedKV() {
//line pkg/tailpipe/gen.qtpl:388
		shadowColor, err := csscolorparser.Parse(kv.Value)
		shadow := kv.Value
		isColor := err == nil
		if err == nil {
			shadow = shadowColor.HexString()
		}

//line pkg/tailpipe/gen.qtpl:394
		qw422016.N().S(`func (ac *AtomicClass) Shadow`)
//line pkg/tailpipe/gen.qtpl:395
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:395
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("shadow", "`)
//line pkg/tailpipe/gen.qtpl:396
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:396
		qw422016.N().S(`", "box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), `)
//line pkg/tailpipe/gen.qtpl:396
		qw422016.E().S(shadow)
//line pkg/tailpipe/gen.qtpl:396
		qw422016.N().S(` 0 0 0 3px")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:399
		if isColor {
//line pkg/tailpipe/gen.qtpl:399
			qw422016.N().S(`
// Box Shadow Opacity
`)
//line pkg/tailpipe/gen.qtpl:401
			for _, opacityKV := range cfg.BoxShadow.Opacity.SortedKV() {
//line pkg/tailpipe/gen.qtpl:403
				opacity, err := strconv.ParseFloat(opacityKV.Value, 64)
				if err != nil {
					log.Printf("%+v XXX %v", opacityKV, err)
					continue
				}
				shadowWithOpacity := shadowColor
				shadowWithOpacity.A = opacity
				shadowWithOpacityStr := shadowWithOpacity.HexString()

//line pkg/tailpipe/gen.qtpl:411
				qw422016.N().S(`func (ac *AtomicClass) Shadow`)
//line pkg/tailpipe/gen.qtpl:412
				qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:412
				qw422016.N().S(`_`)
//line pkg/tailpipe/gen.qtpl:412
				qw422016.E().S(atomicName(opacityKV.Key))
//line pkg/tailpipe/gen.qtpl:412
				qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("shadow","`)
//line pkg/tailpipe/gen.qtpl:413
				qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:413
				qw422016.N().S(`/`)
//line pkg/tailpipe/gen.qtpl:413
				qw422016.E().S(opacityKV.Key)
//line pkg/tailpipe/gen.qtpl:413
				qw422016.N().S(`", "box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), `)
//line pkg/tailpipe/gen.qtpl:413
				qw422016.E().S(shadowWithOpacityStr)
//line pkg/tailpipe/gen.qtpl:413
				qw422016.N().S(` 0 0 0 3px")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:416
			}
//line pkg/tailpipe/gen.qtpl:416
			qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:417
		}
//line pkg/tailpipe/gen.qtpl:417
		qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:418
	}
//line pkg/tailpipe/gen.qtpl:418
	qw422016.N().S(`

// Brightness
`)
//line pkg/tailpipe/gen.qtpl:421
	for _, kv := range cfg.Brightness.SortedKV() {
//line pkg/tailpipe/gen.qtpl:421
		qw422016.N().S(`func (ac *AtomicClass) Brightness`)
//line pkg/tailpipe/gen.qtpl:422
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:422
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("brightness", "`)
//line pkg/tailpipe/gen.qtpl:423
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:423
		qw422016.N().S(`", "filter: brightness(`)
//line pkg/tailpipe/gen.qtpl:423
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:423
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:426
	}
//line pkg/tailpipe/gen.qtpl:426
	qw422016.N().S(`

// Caret Color
`)
//line pkg/tailpipe/gen.qtpl:429
	for _, kv := range cfg.CaretColor.SortedKV() {
//line pkg/tailpipe/gen.qtpl:431
		caretColor, err := csscolorparser.Parse(kv.Value)
		caret := kv.Value
		if err == nil {
			caret = caretColor.HexString()
		}

//line pkg/tailpipe/gen.qtpl:436
		qw422016.N().S(`func (ac *AtomicClass) Caret`)
//line pkg/tailpipe/gen.qtpl:437
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:437
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("caret", "`)
//line pkg/tailpipe/gen.qtpl:438
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:438
		qw422016.N().S(`", "caret-color: `)
//line pkg/tailpipe/gen.qtpl:438
		qw422016.E().S(caret)
//line pkg/tailpipe/gen.qtpl:438
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:441
	}
//line pkg/tailpipe/gen.qtpl:441
	qw422016.N().S(`

// Columns
`)
//line pkg/tailpipe/gen.qtpl:444
	for _, kv := range cfg.Columns.SortedKV() {
//line pkg/tailpipe/gen.qtpl:444
		qw422016.N().S(`func (ac *AtomicClass) Columns`)
//line pkg/tailpipe/gen.qtpl:445
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:445
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("columns", "`)
//line pkg/tailpipe/gen.qtpl:446
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:446
		qw422016.N().S(`", "columns: `)
//line pkg/tailpipe/gen.qtpl:446
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:446
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:449
	}
//line pkg/tailpipe/gen.qtpl:449
	qw422016.N().S(`

// Contrast
`)
//line pkg/tailpipe/gen.qtpl:452
	for _, kv := range cfg.Contrast.SortedKV() {
//line pkg/tailpipe/gen.qtpl:452
		qw422016.N().S(`func (ac *AtomicClass) Contrast`)
//line pkg/tailpipe/gen.qtpl:453
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:453
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("contrast", "`)
//line pkg/tailpipe/gen.qtpl:454
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:454
		qw422016.N().S(`", "filter: contrast(`)
//line pkg/tailpipe/gen.qtpl:454
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:454
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:457
	}
//line pkg/tailpipe/gen.qtpl:457
	qw422016.N().S(`

// Cursor
`)
//line pkg/tailpipe/gen.qtpl:460
	for _, kv := range cfg.Cursor.SortedKV() {
//line pkg/tailpipe/gen.qtpl:460
		qw422016.N().S(`func (ac *AtomicClass) Cursor`)
//line pkg/tailpipe/gen.qtpl:461
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:461
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("cursor", "`)
//line pkg/tailpipe/gen.qtpl:462
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:462
		qw422016.N().S(`", "cursor: `)
//line pkg/tailpipe/gen.qtpl:462
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:462
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:465
	}
//line pkg/tailpipe/gen.qtpl:465
	qw422016.N().S(`

// Divide Width
`)
//line pkg/tailpipe/gen.qtpl:468
	for _, kv := range cfg.Divide.Width.SortedKV() {
//line pkg/tailpipe/gen.qtpl:468
		qw422016.N().S(`func (ac *AtomicClass) DivideX`)
//line pkg/tailpipe/gen.qtpl:469
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:469
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("divide-x", "`)
//line pkg/tailpipe/gen.qtpl:470
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:470
		qw422016.N().S(`","border-right-width: 0px","border-left-width: `)
//line pkg/tailpipe/gen.qtpl:470
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:470
		qw422016.N().S(`")
    return ac
}
func (ac *AtomicClass) DivideY`)
//line pkg/tailpipe/gen.qtpl:473
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:473
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("divide-y", "`)
//line pkg/tailpipe/gen.qtpl:474
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:474
		qw422016.N().S(`","border-bottom-width: 0px","border-top-width: `)
//line pkg/tailpipe/gen.qtpl:474
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:474
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:477
	}
//line pkg/tailpipe/gen.qtpl:477
	qw422016.N().S(`

// Divide Color
`)
//line pkg/tailpipe/gen.qtpl:480
	for _, kv := range cfg.Divide.Color.SortedKV() {
//line pkg/tailpipe/gen.qtpl:482
		divideColor, err := csscolorparser.Parse(kv.Value)
		divide := kv.Value
		isColor := err == nil
		if err == nil {
			divide = divideColor.HexString()
		}

//line pkg/tailpipe/gen.qtpl:488
		qw422016.N().S(`func (ac *AtomicClass) Divide`)
//line pkg/tailpipe/gen.qtpl:489
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:489
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("divide", "`)
//line pkg/tailpipe/gen.qtpl:490
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:490
		qw422016.N().S(`","border-color: `)
//line pkg/tailpipe/gen.qtpl:490
		qw422016.E().S(divide)
//line pkg/tailpipe/gen.qtpl:490
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:493
		if isColor {
//line pkg/tailpipe/gen.qtpl:493
			qw422016.N().S(`
// Divide Color Opacity
`)
//line pkg/tailpipe/gen.qtpl:495
			for _, opacityKV := range cfg.Divide.Opacity.SortedKV() {
//line pkg/tailpipe/gen.qtpl:497
				opacity, err := strconv.ParseFloat(opacityKV.Value, 64)
				if err != nil {
					log.Printf("%+v XXX %v", opacityKV, err)
					continue
				}
				divideWithOpacity := divideColor
				divideWithOpacity.A = opacity
				divideWithOpacityStr := divideWithOpacity.HexString()

//line pkg/tailpipe/gen.qtpl:505
				qw422016.N().S(`func (ac *AtomicClass) Divide`)
//line pkg/tailpipe/gen.qtpl:506
				qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:506
				qw422016.N().S(`_`)
//line pkg/tailpipe/gen.qtpl:506
				qw422016.E().S(atomicName(opacityKV.Key))
//line pkg/tailpipe/gen.qtpl:506
				qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("divide","`)
//line pkg/tailpipe/gen.qtpl:507
				qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:507
				qw422016.N().S(`/`)
//line pkg/tailpipe/gen.qtpl:507
				qw422016.E().S(opacityKV.Key)
//line pkg/tailpipe/gen.qtpl:507
				qw422016.N().S(`", "border-color: `)
//line pkg/tailpipe/gen.qtpl:507
				qw422016.E().S(divideWithOpacityStr)
//line pkg/tailpipe/gen.qtpl:507
				qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:510
			}
//line pkg/tailpipe/gen.qtpl:510
			qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:511
		}
//line pkg/tailpipe/gen.qtpl:511
		qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:512
	}
//line pkg/tailpipe/gen.qtpl:512
	qw422016.N().S(`

// Drop Shadow
`)
//line pkg/tailpipe/gen.qtpl:515
	for _, kv := range cfg.DropShadow.SortedKV() {
//line pkg/tailpipe/gen.qtpl:515
		qw422016.N().S(`func (ac *AtomicClass) DropShadow`)
//line pkg/tailpipe/gen.qtpl:516
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:516
		qw422016.E().S(atomicName(kv.Value))
//line pkg/tailpipe/gen.qtpl:516
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("drop-shadow", "`)
//line pkg/tailpipe/gen.qtpl:517
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:517
		qw422016.N().S(`", "filter: drop-shadow(`)
//line pkg/tailpipe/gen.qtpl:517
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:517
		qw422016.N().S(`)")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:520
	}
//line pkg/tailpipe/gen.qtpl:520
	qw422016.N().S(`

// Fill
`)
//line pkg/tailpipe/gen.qtpl:523
	for _, kv := range cfg.Fill.SortedKV() {
//line pkg/tailpipe/gen.qtpl:523
		qw422016.N().S(`func (ac *AtomicClass) Fill`)
//line pkg/tailpipe/gen.qtpl:524
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:524
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("fill", "`)
//line pkg/tailpipe/gen.qtpl:525
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:525
		qw422016.N().S(`", "fill: `)
//line pkg/tailpipe/gen.qtpl:525
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:525
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:528
	}
//line pkg/tailpipe/gen.qtpl:528
	qw422016.N().S(`

// Flex Basis
`)
//line pkg/tailpipe/gen.qtpl:531
	for _, kv := range cfg.Flex.Basis.SortedKV() {
//line pkg/tailpipe/gen.qtpl:531
		qw422016.N().S(`func (ac *AtomicClass) FlexBasis`)
//line pkg/tailpipe/gen.qtpl:532
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:532
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("flex-basis", "`)
//line pkg/tailpipe/gen.qtpl:533
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:533
		qw422016.N().S(`", "flex-basis: `)
//line pkg/tailpipe/gen.qtpl:533
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:533
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:536
	}
//line pkg/tailpipe/gen.qtpl:536
	qw422016.N().S(`

// Flex Direction
`)
//line pkg/tailpipe/gen.qtpl:539
	for _, kv := range cfg.Flex.Direction.SortedKV() {
//line pkg/tailpipe/gen.qtpl:539
		qw422016.N().S(`func (ac *AtomicClass) FlexDirection`)
//line pkg/tailpipe/gen.qtpl:540
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:540
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("flex", "`)
//line pkg/tailpipe/gen.qtpl:541
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:541
		qw422016.N().S(`", "flex-direction: `)
//line pkg/tailpipe/gen.qtpl:541
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:541
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:544
	}
//line pkg/tailpipe/gen.qtpl:544
	qw422016.N().S(`

// Flex Wrap
`)
//line pkg/tailpipe/gen.qtpl:547
	for _, kv := range cfg.Flex.Wrap.SortedKV() {
//line pkg/tailpipe/gen.qtpl:547
		qw422016.N().S(`func (ac *AtomicClass) FlexWrap`)
//line pkg/tailpipe/gen.qtpl:548
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:548
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("flex-wrap", "`)
//line pkg/tailpipe/gen.qtpl:549
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:549
		qw422016.N().S(`", "flex-wrap: `)
//line pkg/tailpipe/gen.qtpl:549
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:549
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:552
	}
//line pkg/tailpipe/gen.qtpl:552
	qw422016.N().S(`

// Flex
`)
//line pkg/tailpipe/gen.qtpl:555
	for _, kv := range cfg.Flex.Value.SortedKV() {
//line pkg/tailpipe/gen.qtpl:555
		qw422016.N().S(`func (ac *AtomicClass) Flex`)
//line pkg/tailpipe/gen.qtpl:556
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:556
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("flex", "`)
//line pkg/tailpipe/gen.qtpl:557
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:557
		qw422016.N().S(`", "flex: `)
//line pkg/tailpipe/gen.qtpl:557
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:557
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:560
	}
//line pkg/tailpipe/gen.qtpl:560
	qw422016.N().S(`


// Flex Grow
`)
//line pkg/tailpipe/gen.qtpl:564
	for _, kv := range cfg.Flex.Grow.SortedKV() {
//line pkg/tailpipe/gen.qtpl:564
		qw422016.N().S(`func (ac *AtomicClass) FlexGrow`)
//line pkg/tailpipe/gen.qtpl:565
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:565
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("flex-grow", "`)
//line pkg/tailpipe/gen.qtpl:566
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:566
		qw422016.N().S(`", "flex-grow: `)
//line pkg/tailpipe/gen.qtpl:566
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:566
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:569
	}
//line pkg/tailpipe/gen.qtpl:569
	qw422016.N().S(`

// Flex Shrink
`)
//line pkg/tailpipe/gen.qtpl:572
	for _, kv := range cfg.Flex.Shrink.SortedKV() {
//line pkg/tailpipe/gen.qtpl:572
		qw422016.N().S(`func (ac *AtomicClass) FlexShrink`)
//line pkg/tailpipe/gen.qtpl:573
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:573
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("flex-shrink", "`)
//line pkg/tailpipe/gen.qtpl:574
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:574
		qw422016.N().S(`", "flex-shrink: `)
//line pkg/tailpipe/gen.qtpl:574
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:574
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:577
	}
//line pkg/tailpipe/gen.qtpl:577
	qw422016.N().S(`

// Fonts
// Font Family
`)
//line pkg/tailpipe/gen.qtpl:581
	for _, kv := range cfg.Font.Family.SortedKV() {
//line pkg/tailpipe/gen.qtpl:581
		qw422016.N().S(`func (ac *AtomicClass) Font`)
//line pkg/tailpipe/gen.qtpl:582
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:582
		qw422016.E().S(atomicName(kv.Value))
//line pkg/tailpipe/gen.qtpl:582
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("font", "`)
//line pkg/tailpipe/gen.qtpl:583
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:583
		qw422016.N().S(`", "font-family: `)
//line pkg/tailpipe/gen.qtpl:583
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:583
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:586
	}
//line pkg/tailpipe/gen.qtpl:586
	qw422016.N().S(`

// Font Size
`)
//line pkg/tailpipe/gen.qtpl:589
	for k, size := range cfg.Font.Size {
//line pkg/tailpipe/gen.qtpl:589
		qw422016.N().S(`func (ac *AtomicClass) Text`)
//line pkg/tailpipe/gen.qtpl:590
		qw422016.E().S(atomicName(k))
//line pkg/tailpipe/gen.qtpl:590
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("text", "`)
//line pkg/tailpipe/gen.qtpl:591
		qw422016.E().S(k)
//line pkg/tailpipe/gen.qtpl:591
		qw422016.N().S(`",
        "font-size: `)
//line pkg/tailpipe/gen.qtpl:592
		qw422016.E().S(size.Value)
//line pkg/tailpipe/gen.qtpl:592
		qw422016.N().S(`",
        "line-height: `)
//line pkg/tailpipe/gen.qtpl:593
		qw422016.E().S(size.LineHeight)
//line pkg/tailpipe/gen.qtpl:593
		qw422016.N().S(`",
    )
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:597
	}
//line pkg/tailpipe/gen.qtpl:597
	qw422016.N().S(`

// Font Smoothing
`)
//line pkg/tailpipe/gen.qtpl:600
	for _, kv := range cfg.Font.Smoothing.SortedKV() {
//line pkg/tailpipe/gen.qtpl:600
		qw422016.N().S(`func (ac *AtomicClass) FontSmoothing`)
//line pkg/tailpipe/gen.qtpl:601
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:601
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("antialiased", "`)
//line pkg/tailpipe/gen.qtpl:602
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:602
		qw422016.N().S(`", "font-smoothing: `)
//line pkg/tailpipe/gen.qtpl:602
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:602
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:605
	}
//line pkg/tailpipe/gen.qtpl:605
	qw422016.N().S(`

// Font Style
`)
//line pkg/tailpipe/gen.qtpl:608
	for _, kv := range cfg.Font.Style.SortedKV() {
//line pkg/tailpipe/gen.qtpl:608
		qw422016.N().S(`func (ac *AtomicClass) FontStyle`)
//line pkg/tailpipe/gen.qtpl:609
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:609
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("font", "`)
//line pkg/tailpipe/gen.qtpl:610
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:610
		qw422016.N().S(`", "font-style: `)
//line pkg/tailpipe/gen.qtpl:610
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:610
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:613
	}
//line pkg/tailpipe/gen.qtpl:613
	qw422016.N().S(`

// Font Weight
`)
//line pkg/tailpipe/gen.qtpl:616
	for _, kv := range cfg.Font.Weight.SortedKV() {
//line pkg/tailpipe/gen.qtpl:616
		qw422016.N().S(`func (ac *AtomicClass) Font`)
//line pkg/tailpipe/gen.qtpl:617
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:617
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("font", "`)
//line pkg/tailpipe/gen.qtpl:618
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:618
		qw422016.N().S(`", "font-weight: `)
//line pkg/tailpipe/gen.qtpl:618
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:618
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:621
	}
//line pkg/tailpipe/gen.qtpl:621
	qw422016.N().S(`

// Font Variant Numeric
`)
//line pkg/tailpipe/gen.qtpl:624
	for _, kv := range cfg.Font.VariantNumeric.SortedKV() {
//line pkg/tailpipe/gen.qtpl:624
		qw422016.N().S(`func (ac *AtomicClass) FontVariantNumeric`)
//line pkg/tailpipe/gen.qtpl:625
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:625
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("font-variant-numeric", "`)
//line pkg/tailpipe/gen.qtpl:626
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:626
		qw422016.N().S(`", "font-variant-numeric: `)
//line pkg/tailpipe/gen.qtpl:626
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:626
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:629
	}
//line pkg/tailpipe/gen.qtpl:629
	qw422016.N().S(`


// Letter Spacing
`)
//line pkg/tailpipe/gen.qtpl:633
	for _, kv := range cfg.LetterSpacing.SortedKV() {
//line pkg/tailpipe/gen.qtpl:633
		qw422016.N().S(`func (ac *AtomicClass) Tracking`)
//line pkg/tailpipe/gen.qtpl:634
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:634
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("tracking", "`)
//line pkg/tailpipe/gen.qtpl:635
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:635
		qw422016.N().S(`", "letter-spacing: `)
//line pkg/tailpipe/gen.qtpl:635
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:635
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:638
	}
//line pkg/tailpipe/gen.qtpl:638
	qw422016.N().S(`

// Line Height
`)
//line pkg/tailpipe/gen.qtpl:641
	for _, kv := range cfg.LineHeight.SortedKV() {
//line pkg/tailpipe/gen.qtpl:641
		qw422016.N().S(`func (ac *AtomicClass) Leading`)
//line pkg/tailpipe/gen.qtpl:642
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:642
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("leading", "`)
//line pkg/tailpipe/gen.qtpl:643
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:643
		qw422016.N().S(`", "line-height: `)
//line pkg/tailpipe/gen.qtpl:643
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:643
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:646
	}
//line pkg/tailpipe/gen.qtpl:646
	qw422016.N().S(`

// List Style Type
`)
//line pkg/tailpipe/gen.qtpl:649
	for _, kv := range cfg.ListStyleType.SortedKV() {
//line pkg/tailpipe/gen.qtpl:649
		qw422016.N().S(`func (ac *AtomicClass) ListStyle`)
//line pkg/tailpipe/gen.qtpl:650
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:650
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("list", "`)
//line pkg/tailpipe/gen.qtpl:651
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:651
		qw422016.N().S(`", "list-style-type: `)
//line pkg/tailpipe/gen.qtpl:651
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:651
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:654
	}
//line pkg/tailpipe/gen.qtpl:654
	qw422016.N().S(`

// List Style Position
`)
//line pkg/tailpipe/gen.qtpl:657
	for _, kv := range cfg.ListStylePosition.SortedKV() {
//line pkg/tailpipe/gen.qtpl:657
		qw422016.N().S(`func (ac *AtomicClass) ListStyle`)
//line pkg/tailpipe/gen.qtpl:658
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:658
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("list", "`)
//line pkg/tailpipe/gen.qtpl:659
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:659
		qw422016.N().S(`", "list-style-position: `)
//line pkg/tailpipe/gen.qtpl:659
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:659
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:662
	}
//line pkg/tailpipe/gen.qtpl:662
	qw422016.N().S(`

// Text Align
`)
//line pkg/tailpipe/gen.qtpl:665
	for _, kv := range cfg.Text.Align.SortedKV() {
//line pkg/tailpipe/gen.qtpl:665
		qw422016.N().S(`func (ac *AtomicClass) Text`)
//line pkg/tailpipe/gen.qtpl:666
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:666
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("text", "`)
//line pkg/tailpipe/gen.qtpl:667
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:667
		qw422016.N().S(`", "text-align: `)
//line pkg/tailpipe/gen.qtpl:667
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:667
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:670
	}
//line pkg/tailpipe/gen.qtpl:670
	qw422016.N().S(`

// Text Color
`)
//line pkg/tailpipe/gen.qtpl:673
	for _, kv := range cfg.Text.Color.SortedKV() {
//line pkg/tailpipe/gen.qtpl:675
		textColor, err := csscolorparser.Parse(kv.Value)
		text := kv.Value
		isColor := err == nil
		if err == nil {
			text = textColor.HexString()
		}

//line pkg/tailpipe/gen.qtpl:681
		qw422016.N().S(`func (ac *AtomicClass) Text`)
//line pkg/tailpipe/gen.qtpl:682
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:682
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("text", "`)
//line pkg/tailpipe/gen.qtpl:683
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:683
		qw422016.N().S(`", "color: `)
//line pkg/tailpipe/gen.qtpl:683
		qw422016.E().S(text)
//line pkg/tailpipe/gen.qtpl:683
		qw422016.N().S(`")
    return ac
}

`)
//line pkg/tailpipe/gen.qtpl:687
		if isColor {
//line pkg/tailpipe/gen.qtpl:687
			qw422016.N().S(`

// Text Opacity
`)
//line pkg/tailpipe/gen.qtpl:690
			for _, opacityKV := range cfg.Text.Opacity.SortedKV() {
//line pkg/tailpipe/gen.qtpl:692
				opacity, err := strconv.ParseFloat(opacityKV.Value, 64)
				if err != nil {
					log.Printf("%+v XXX %v", opacityKV, err)
					continue
				}
				textWithOpacity := textColor
				textWithOpacity.A = opacity
				textWithOpacityStr := textWithOpacity.HexString()

//line pkg/tailpipe/gen.qtpl:700
				qw422016.N().S(`func (ac *AtomicClass) Text`)
//line pkg/tailpipe/gen.qtpl:701
				qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:701
				qw422016.N().S(`_`)
//line pkg/tailpipe/gen.qtpl:701
				qw422016.E().S(atomicName(opacityKV.Key))
//line pkg/tailpipe/gen.qtpl:701
				qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("text","`)
//line pkg/tailpipe/gen.qtpl:702
				qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:702
				qw422016.N().S(`/`)
//line pkg/tailpipe/gen.qtpl:702
				qw422016.E().S(opacityKV.Key)
//line pkg/tailpipe/gen.qtpl:702
				qw422016.N().S(`", "color: `)
//line pkg/tailpipe/gen.qtpl:702
				qw422016.E().S(textWithOpacityStr)
//line pkg/tailpipe/gen.qtpl:702
				qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:705
			}
//line pkg/tailpipe/gen.qtpl:705
			qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:706
		}
//line pkg/tailpipe/gen.qtpl:706
		qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:707
	}
//line pkg/tailpipe/gen.qtpl:707
	qw422016.N().S(`

// Text Decoration
`)
//line pkg/tailpipe/gen.qtpl:710
	for _, kv := range cfg.Text.Decoration.SortedKV() {
//line pkg/tailpipe/gen.qtpl:710
		qw422016.N().S(`func (ac *AtomicClass) Text`)
//line pkg/tailpipe/gen.qtpl:711
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:711
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("text", "`)
//line pkg/tailpipe/gen.qtpl:712
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:712
		qw422016.N().S(`", "text-decoration: `)
//line pkg/tailpipe/gen.qtpl:712
		qw422016.E().S(kv.Value)
//line pkg/tailpipe/gen.qtpl:712
		qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:715
	}
//line pkg/tailpipe/gen.qtpl:715
	qw422016.N().S(`

// Text Decoration Color
`)
//line pkg/tailpipe/gen.qtpl:718
	for _, kv := range cfg.Text.DecorationColor.SortedKV() {
//line pkg/tailpipe/gen.qtpl:720
		textDecorationColor, err := csscolorparser.Parse(kv.Value)
		text := kv.Value
		isColor := err == nil
		if err == nil {
			text = textDecorationColor.HexString()
		}

//line pkg/tailpipe/gen.qtpl:726
		qw422016.N().S(`func (ac *AtomicClass) Decoration`)
//line pkg/tailpipe/gen.qtpl:727
		qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:727
		qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("decoration", "`)
//line pkg/tailpipe/gen.qtpl:728
		qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:728
		qw422016.N().S(`", "text-decoration-color: `)
//line pkg/tailpipe/gen.qtpl:728
		qw422016.E().S(text)
//line pkg/tailpipe/gen.qtpl:728
		qw422016.N().S(`")
    return ac
}

`)
//line pkg/tailpipe/gen.qtpl:732
		if isColor {
//line pkg/tailpipe/gen.qtpl:732
			qw422016.N().S(`
// Text Decoration Opacity
`)
//line pkg/tailpipe/gen.qtpl:734
			for _, opacityKV := range cfg.Text.Opacity.SortedKV() {
//line pkg/tailpipe/gen.qtpl:736
				opacity, err := strconv.ParseFloat(opacityKV.Value, 64)
				if err != nil {
					log.Printf("%+v XXX %v", opacityKV, err)
					continue
				}
				textDecorationColorWithOpacity := textDecorationColor
				textDecorationColorWithOpacity.A = opacity
				textDecorationColorWithOpacityStr := textDecorationColorWithOpacity.HexString()

//line pkg/tailpipe/gen.qtpl:744
				qw422016.N().S(`func (ac *AtomicClass) Decoration`)
//line pkg/tailpipe/gen.qtpl:745
				qw422016.E().S(atomicName(kv.Key))
//line pkg/tailpipe/gen.qtpl:745
				qw422016.N().S(`_`)
//line pkg/tailpipe/gen.qtpl:745
				qw422016.E().S(atomicName(opacityKV.Key))
//line pkg/tailpipe/gen.qtpl:745
				qw422016.N().S(`() *AtomicClass {
    ac.upsertClass("decoration","`)
//line pkg/tailpipe/gen.qtpl:746
				qw422016.E().S(kv.Key)
//line pkg/tailpipe/gen.qtpl:746
				qw422016.N().S(`/`)
//line pkg/tailpipe/gen.qtpl:746
				qw422016.E().S(opacityKV.Key)
//line pkg/tailpipe/gen.qtpl:746
				qw422016.N().S(`", "color: `)
//line pkg/tailpipe/gen.qtpl:746
				qw422016.E().S(textDecorationColorWithOpacityStr)
//line pkg/tailpipe/gen.qtpl:746
				qw422016.N().S(`")
    return ac
}
`)
//line pkg/tailpipe/gen.qtpl:749
			}
//line pkg/tailpipe/gen.qtpl:749
			qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:750
		}
//line pkg/tailpipe/gen.qtpl:750
		qw422016.N().S(`
`)
//line pkg/tailpipe/gen.qtpl:751
	}
//line pkg/tailpipe/gen.qtpl:751
	qw422016.N().S(`

`)
//line pkg/tailpipe/gen.qtpl:753
}

//line pkg/tailpipe/gen.qtpl:753
func writegenerateFromConfig(qq422016 qtio422016.Writer, cfg TailPipeConfig) {
//line pkg/tailpipe/gen.qtpl:753
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/tailpipe/gen.qtpl:753
	streamgenerateFromConfig(qw422016, cfg)
//line pkg/tailpipe/gen.qtpl:753
	qt422016.ReleaseWriter(qw422016)
//line pkg/tailpipe/gen.qtpl:753
}

//line pkg/tailpipe/gen.qtpl:753
func generateFromConfig(cfg TailPipeConfig) string {
//line pkg/tailpipe/gen.qtpl:753
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/tailpipe/gen.qtpl:753
	writegenerateFromConfig(qb422016, cfg)
//line pkg/tailpipe/gen.qtpl:753
	qs422016 := string(qb422016.B)
//line pkg/tailpipe/gen.qtpl:753
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/tailpipe/gen.qtpl:753
	return qs422016
//line pkg/tailpipe/gen.qtpl:753
}
